# Generated by Django 3.2 on 2021-04-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210429_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.note')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.note')),
            ],
        ),
    ]
