version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    image: kaustubhnair/mindnotesbackend
    build:
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - ./logs:/code/logs
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: kaustubhnair/mindnotesfrontend
    build: 
      dockerfile: ./frontend/Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  nginx:
    image: kaustubhnair/mindnotesnginx
    restart: always
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
