---
- name: Deploy calculator
  hosts: hosts
  tasks:
    - name: Pull docker images
      shell:
        chdir: mind-notes
        cmd: docker-compose -f docker-compose-prod.yml pull
    - name: Start containers
      shell:
        chdir: mind-notes
        cmd: docker-compose -f docker-compose-prod.yml up -d
