# Generated by Django 3.2 on 2021-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='note',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
