# Generated by Django 3.2 on 2021-04-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
            preserve_default=False,
        ),
    ]
