# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LS
        run: |
          ls
      - name: Build container
        run: |
          docker-compose up --build -d
      - name: Run migrations
        run: |
          docker-compose exec -T web python manage.py migrate

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: |
          docker-compose up --build -d
      - name: Run migrations
        run: |
          docker-compose exec -T web python manage.py migrate
      - name: Run tests
        run: |
          docker-compose exec -T web python manage.py test

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build container
        run: |
          docker-compose build
      - name: Push to docker hub
        run: |
          docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - uses: actions/checkout@v2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ansible
          inventory: |
              [hosts]
              server1 ansible_host=104.41.156.91

              [all:vars]
              ansible_user=kaustubh
              ansible_ssh_pass=${{secrets.ANSIBLE_SSH_PASSWORD}}
