# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: |
        docker-compose up --build -d
    - name: Run migrations
      run: |
        docker-compose exec web python manage.py migrate

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: |
        docker-compose up --build -d
    - name: Run migrations
      run: |
        docker-compose exec web python manage.py migrate
    - name: Run tests
      run: |
        docker-compose exec web python manage.py test
